modLoader = "javafml"
license = "MIT license"
loaderVersion = "[43,)"
#issueTrackerURL=""

[[mods]]
modId = "windowlogging"
version = "0.0.9"
displayName = "Windowlogging"
#updateJSONURL=""
authors = "Simibubi, Grimmauld"
description = '''
Windowlogging, ported from Create 1.14.4'''

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"